### ISSUE TITLE
모델 공개는 안하시는건가요?

### ISSUE THREAD

**Issue by didw** [KB-Bank-AI/KB-ALBERT-KO#1]
이메일로 신청받는다고 써져있는데 고려후 답준다는 말 이후 연락이 없으시네요.

**Comment by KB-Bank-AI** [comment]
안녕하세요?
 
AI혁신센터 김형철 팀장입니다.
 
현재 내부적으로 법률검토 진행 중에 있습니다.
 
최대한 빨리 사용 가능 메일을 안내 드릴 수 있도록 노력하겠습니다.
 
감사합니다.
 


-----------------------원본 메세지-----------------------
보낸사람: "Jongyeol Yang "<notifications@github.com>
받는사람: KB-Bank-AI/KB-ALBERT-KO <KB-ALBERT-KO@noreply.github.com>
참조: Subscribed <subscribed@noreply.github.com>
보낸시간: 2020-08-18 14:37:03 GMT +0900 (Asia/Seoul)
제목: [KB-Bank-AI/KB-ALBERT-KO] 모델 공개는 안하시는건가요? (#1)
 
 
 
이메일로 신청받는다고 써져있는데 고려후 답준다는 말 이후 연락이 없으시네요.
