### ISSUE TITLE
tokenizer = AlbertTokenizer.from_pretrained(kb_albert_model_path) 에서 에러가 납니다

### ISSUE THREAD

**Issue by rlaalstn1504** [KB-Bank-AI/KB-ALBERT-KO#4]
tokenizer = AlbertTokenizer.from_pretrained(model_path) 부분을 실행하면 TypeError: not a string 에러가 뜹니다.  
python 3.8
transformers 4.9.1 입니다.
에러 전문은 다음과 같습니다. 구글링 해도 해답 찾기가 쉽지가 않네요ㅜ
TypeError                                 Traceback (most recent call last)
<ipython-input-5-bd6f95c71348> in <module>
----> 1 tokenizer = AlbertTokenizer.from_pretrained('model')

~\anaconda3\envs\minsu\lib\site-packages\transformers\tokenization_utils_base.py in from_pretrained(cls, pretrained_model_name_or_path, *init_inputs, **kwargs)
   1730                 logger.info(f"loading file {file_path} from cache at {resolved_vocab_files[file_id]}")
   1731 
-> 1732         return cls._from_pretrained(
   1733             resolved_vocab_files, pretrained_model_name_or_path, init_configuration, *init_inputs, **kwargs
   1734         )

~\anaconda3\envs\minsu\lib\site-packages\transformers\tokenization_utils_base.py in _from_pretrained(cls, resolved_vocab_files, pretrained_model_name_or_path, init_configuration, *init_inputs, **kwargs)
   1848         # Instantiate tokenizer.
   1849         try:
-> 1850             tokenizer = cls(*init_inputs, **init_kwargs)
   1851         except OSError:
   1852             raise OSError(

~\anaconda3\envs\minsu\lib\site-packages\transformers\models\albert\tokenization_albert.py in __init__(self, vocab_file, do_lower_case, remove_space, keep_accents, bos_token, eos_token, unk_token, sep_token, pad_token, cls_token, mask_token, sp_model_kwargs, **kwargs)
    169 
    170         self.sp_model = spm.SentencePieceProcessor(**self.sp_model_kwargs)
--> 171         self.sp_model.Load(vocab_file)
    172 
    173     @property

~\anaconda3\envs\minsu\lib\site-packages\sentencepiece\__init__.py in Load(self, model_file, model_proto)
    365       if model_proto:
    366         return self.LoadFromSerializedProto(model_proto)
--> 367       return self.LoadFromFile(model_file)
    368 
    369 

~\anaconda3\envs\minsu\lib\site-packages\sentencepiece\__init__.py in LoadFromFile(self, arg)
    169 
    170     def LoadFromFile(self, arg):
--> 171         return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
    172 
    173     def DecodeIdsWithCheck(self, ids):

TypeError: not a string

**Comment by sackoh** [comment]
AlbertTokenizer 는 sentencepiece를 베이스로 하고 있어서 에러가 납니다.
아래 토크나이저 사용 방법에 따라 사용하시면 문제없이 사용 가능하실 것으로 보입니다.
https://github.com/KB-Bank-AI/KB-ALBERT-KO/tree/master/kb-albert-char

그래도 에러가 나신다면 transformers 버전을 3.x로 낮춰서 해주시면 감사하겠습니다.
