### ISSUE TITLE
현재 모델파일은 어떻게 받아야하나요?

### ISSUE THREAD

**Issue by rjh7008** [KB-Bank-AI/KB-ALBERT-KO#5]
안녕하세요.
Kb-albert모델을 사용해보고싶은데 현재 모델파일을 신청하는 메일 주소(ai.kbg@kbfg.com)로 메일 전송이 불가능한 상태입니다.
모델 공개가 불가능한 것인지 신청방법이 변경된 것인지 알수 없어 남깁니다.

**Comment by snoop2head** [comment]
@rjh7008 
혹시 아직도 이메일 전송이 불가능한 상태인가요? 저는 방금 요청 이메일을 보냈는데, 아직 반송되지 않은 것 같습니다.

**Comment by KB-Bank-AI** [comment]
안녕하세요
			평생금융파트너 KB국민은행 금융AI센터입니다.
			
			첨부된 파일을 열기 위해서 아래의 비밀번호를 입력하셔야 합니다.
			
			      kb-albert-char-0827
			
			첨부된 파일의 다운로드 가능 기간은 발신일로부터 7일 이내 입니다.
			발신드린 이메일 이외의 공유는 삼가해주시기 바랍니다.
			감사합니다.
			
		
		
			
			 
		
	


 

\n
- ${ message.title }\n
${ bigfile.fileName }(32.5 MB) - https://webmail.kbfg.com/kbmail/mail/security/bigfile/download.do?a=NjFlOGE5Y2EzZmU2YmIzOTg4ZDc3MmRhOzYxZThhOWM5M2ZkNmE3ODU3Y2JiNzE4NA==\n (Expire : ${ bigfile.downTerm } )\n

**Comment by snoop2head** [comment]
@KB-Bank-AI 감사합니다! 보내주신 모델 잘 사용하도록 하겠습니다 ㅎㅎ
